version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
